/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wordpress;

import java.sql.Connection;
import javax.swing.DefaultListModel;


public class MainMenu extends javax.swing.JFrame {

    Connection conn;
   private final int idUser;
    public MainMenu() {
        initComponents();
        idUser=0;
    }
    
    public MainMenu(int user) {
        initComponents();
        idUser=user;
    }

    public int getIdUser() {
        return idUser;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NewArticleButton = new javax.swing.JButton();
        SeeArticleButton = new javax.swing.JButton();
        SeeDraftsButton = new javax.swing.JButton();
        ChangeAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Main Menu");

        NewArticleButton.setText("New Article");
        NewArticleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewArticleButtonActionPerformed(evt);
            }
        });

        SeeArticleButton.setText("See Articles");
        SeeArticleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeArticleButtonActionPerformed(evt);
            }
        });

        SeeDraftsButton.setText("See Drafts");
        SeeDraftsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeDraftsButtonActionPerformed(evt);
            }
        });

        ChangeAccountButton.setText("Change Account");
        ChangeAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChangeAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addGap(294, 294, 294))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewArticleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(SeeArticleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(SeeDraftsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(87, 87, 87)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewArticleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(SeeArticleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(SeeDraftsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(193, 193, 193)
                .addComponent(ChangeAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewArticleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewArticleButtonActionPerformed
        CreateArticle article = new CreateArticle(getIdUser());
            article.setVisible(true);
            setVisible(false);
            dispose();
    }//GEN-LAST:event_NewArticleButtonActionPerformed

    private void ChangeAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeAccountButtonActionPerformed
        Login log= new Login();
        log.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_ChangeAccountButtonActionPerformed

    private void SeeArticleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeArticleButtonActionPerformed
        SeeArticle article= new SeeArticle(getIdUser());
        article.showArticle();
        
        article.setVisible(true);
        //article.getEditArticleButton().setVisible(false);
        //article.getDeleteArticleButton().setVisible(false);
        setVisible(false);
        //dispose();
        
    }//GEN-LAST:event_SeeArticleButtonActionPerformed

    private void SeeDraftsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeDraftsButtonActionPerformed
       SeeDrafts draft= new SeeDrafts(getIdUser());
        draft.showDrafts();
        draft.setVisible(true);
        //article.getEditArticleButton().setVisible(false);
        //article.getDeleteArticleButton().setVisible(false);
        setVisible(false);
        //dispose();
    }//GEN-LAST:event_SeeDraftsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeAccountButton;
    private javax.swing.JButton NewArticleButton;
    private javax.swing.JButton SeeArticleButton;
    private javax.swing.JButton SeeDraftsButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

        
}
