/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wordpress;

import com.sun.org.apache.xerces.internal.impl.dv.dtd.IDDatatypeValidator;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import static java.nio.file.Files.list;
import static java.rmi.Naming.list;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.util.Collections.list;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.ListModel;


public class SeeArticle extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet result = null;
    Statement statement = null;
    private final int idUser;

    public SeeArticle() {
        initComponents();
        idUser = 0;
    }

    public SeeArticle(int user) {
        initComponents();
        
        idUser = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaArticole = new javax.swing.JList<>();
        IdLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        PublishedArticle = new javax.swing.JLabel();
        DeleteArticleButton = new javax.swing.JButton();
        EditArticleButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaArticole.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaArticole.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ListaArticoleComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(ListaArticole);

        IdLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        IdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdLabel.setText("Id");

        TitleLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Title");

        DateLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        DateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLabel.setText("Date");

        UserLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        UserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLabel.setText("User");

        PublishedArticle.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        PublishedArticle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PublishedArticle.setText("Published Articles");

        DeleteArticleButton.setText("Delete Article");
        DeleteArticleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteArticleButtonActionPerformed(evt);
            }
        });

        EditArticleButton.setText("Edit Article");
        EditArticleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditArticleButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(PublishedArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(EditArticleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteArticleButton)
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(PublishedArticle, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteArticleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditArticleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(BackButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaArticoleComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ListaArticoleComponentAdded

    }//GEN-LAST:event_ListaArticoleComponentAdded

    private void DeleteArticleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteArticleButtonActionPerformed
         try{
        String value = ListaArticole.getSelectedValue();
          value= value.substring(0, value.indexOf(" "));
        int idArticol = Integer.parseInt(value);
        if(idArticol!=-1){
         
        String deleteQuery="delete from publish where id_publish = ?";
        try {
            Wordpress a=new Wordpress();
            conn = a.ConnectDB();
            pst = conn.prepareStatement(deleteQuery);
            pst.setInt(1,idArticol);
            pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(SeeArticle.class.getName()).log(Level.SEVERE, null, ex);
        }
       ((DefaultListModel) ListaArticole.getModel()).remove(ListaArticole.getSelectedIndex());
       
        ListaArticole.updateUI();
        }
         }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Please select an article", "Article not selected", JOptionPane.ERROR_MESSAGE);
     
                }
    }//GEN-LAST:event_DeleteArticleButtonActionPerformed

    private void EditArticleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditArticleButtonActionPerformed
       try{ 
        String value = ListaArticole.getSelectedValue();
        value= value.substring(0, value.indexOf(" "));
        int idArticol = Integer.parseInt(value);
        EditArticle editArticle = new EditArticle(idUser, idArticol);
        editArticle.showTitleAndText(idUser, idArticol);
        System.out.println(idArticol);
        editArticle.setVisible(true);
        setVisible(false);
        //System.out.println(idArticle);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please select an article", "Article not selected", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditArticleButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
       backToSeeArticle();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeeArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeeArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeeArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeeArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeeArticle().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton DeleteArticleButton;
    private javax.swing.JButton EditArticleButton;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JList<String> ListaArticole;
    private javax.swing.JLabel PublishedArticle;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
DefaultListModel dim;
    public void showArticle() {
        try {
            dim = new DefaultListModel();
            Wordpress a=new Wordpress();
        conn = a.ConnectDB();
            statement = conn.createStatement();
            result = statement.executeQuery("SELECT id_publish,id_user, publish_name, publish_date, username, views\n"
                    + "FROM publish\n"
                    + "JOIN user ON(id_user=iduser);");
            
            while (result.next()) {
                System.out.println(result.getInt("id_user"));
                if(idUser == result.getInt("id_user"))
                dim.addElement(String.format("%-10s %15s %n", result.getInt("id_publish"), result.getString("publish_name"))
                        + String.format("%25s %25s ", result.getDate("publish_date"), result.getString("username")));
             }
            ListaArticole.setModel(dim);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                result.close();
            } catch (Exception e) {
                /* ignored */ }
            try {
                pst.close();
            } catch (Exception e) {
                /* ignored */ }
            try {
                conn.close();
            } catch (Exception e) {
                /* ignored */ }
        }
    }

    public JButton getDeleteArticleButton() {
        return DeleteArticleButton;
    }

    public void setDeleteArticleButton(JButton DeleteArticleButton) {
        this.DeleteArticleButton = DeleteArticleButton;
    }

    public JButton getEditArticleButton() {
        return EditArticleButton;
    }

    public void setEditArticleButton(JButton EditArticleButton) {
        this.EditArticleButton = EditArticleButton;
    }
    public void deteleArticle(){
        
    }
    public void backToSeeArticle() {
        MainMenu main = new MainMenu(idUser);
        main.setVisible(true);
        setVisible(false);
        dispose();
    }
}
